blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/bakeronchain/learnvault/discussions
    about: Please ask and answer questions here
  - name: Security Vulnerability
    url: https://github.com/bakeronchain/learnvault/security/advisories
    about: Please report security vulnerabilities privately
